version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
